[project]
name = "src"
version = "0.0.1"
authors = [{name = "Haseeb Asif", email = "haseebasif5@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}